"use client";

import { useState } from "react";
import { jsPDF } from "jspdf";
import { Loader2, CheckCircle, HardHat, ShieldCheck, Lock } from "lucide-react";

export default function Home() {
  const [loading, setLoading] = useState(false);
  const [generated, setGenerated] = useState(false);
  const [formData, setFormData] = useState({
    trade: "Electrician",
    company: "",
    job: "",
    accessCode: "",
  });
  const [hazards, setHazards] = useState<string[]>([]);

  const handleHazardToggle = (hazard: string) => {
    setHazards((prev) =>
      prev.includes(hazard)
        ? prev.filter((h) => h !== hazard)
        : [...prev, hazard]
    );
  };

  const generateRAMS = async () => {
    // 1. Validation
    if (formData.accessCode !== "PRO2025") {
      alert("❌ Invalid Access Code. Please use: PRO2025");
      return;
    }
    if (!formData.company || !formData.job) {
      alert("⚠️ Please fill in Company Name and Job Description.");
      return;
    }

    setLoading(true);
    setGenerated(false);

    try {
      // 2. Send Request
      const res = await fetch("/api/generate", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ ...formData, hazards }),
      });

      // 3. Handle Errors
      const data = await res.json();

      if (!res.ok) {
        // If server sends an error, show it!
        throw new Error(data.error || "Server Error");
      }
      
      if (data.text) {
        createPDF(data.text);
        setGenerated(true);
      }

    } catch (error: any) {
      console.error(error);
      alert(`❌ Error: ${error.message}`);
    } finally {
      setLoading(false);
    }
  };

  const createPDF = (text: string) => {
    const doc = new jsPDF();
    
    // Header
    doc.setFont("helvetica", "bold");
    doc.setFontSize(22);
    doc.text("RAMS Sorted | Compliance", 105, 20, { align: "center" });
    
    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    doc.text("Generated by RAMS Sorted - Official Document", 105, 28, { align: "center" });
    
    doc.setLineWidth(0.5);
    doc.line(20, 35, 190, 35); 

    // Content
    doc.setFontSize(11);
    const splitText = doc.splitTextToSize(text, 170);
    doc.text(splitText, 20, 45);
    
    // Save
    doc.save(`RAMS_${formData.company.replace(/ /g, "_")}_${new Date().toISOString().split('T')[0]}.pdf`);
  };

  return (
    <div className="min-h-screen bg-white font-sans text-black">
      {/* Navbar */}
      <nav className="border-b border-gray-200 py-4 px-6 flex justify-between items-center sticky top-0 bg-white/90 backdrop-blur-md z-50">
        <div className="flex items-center gap-2 font-bold text-xl tracking-tighter">
          <ShieldCheck className="w-6 h-6" />
          RAMS Sorted
        </div>
        <div className="text-xs font-bold bg-black text-white px-3 py-1 rounded-full">PRO EDITION</div>
      </nav>

      <main className="max-w-2xl mx-auto py-12 px-4">
        <div className="text-center mb-10">
          <h1 className="text-4xl font-extrabold mb-4 tracking-tight">Compliance. <span className="text-gray-400">Done.</span></h1>
          <p className="text-gray-500 text-lg">Generate UK-compliant safety documents in 30 seconds.</p>
        </div>

        <div className="bg-gray-50 rounded-2xl border border-gray-200 p-8 shadow-sm">
          
          {/* Login Gate */}
          <div className="mb-8">
            <label className="flex items-center gap-2 text-xs font-bold uppercase tracking-wider text-gray-500 mb-2">
              <Lock className="w-3 h-3" /> Pro Access Code
            </label>
            <input
              type="password"
              placeholder="Enter Code (PRO2025)"
              className="w-full bg-white border border-gray-300 rounded-lg px-4 py-3 focus:ring-2 focus:ring-black outline-none transition"
              onChange={(e) => setFormData({ ...formData, accessCode: e.target.value })}
            />
          </div>

          <div className="space-y-6">
            <div className="grid grid-cols-2 gap-4">
              <div>
                <label className="block text-sm font-bold mb-2">Trade</label>
                <select
                  className="w-full bg-white border border-gray-300 rounded-lg px-4 py-3 outline-none focus:border-black"
                  onChange={(e) => setFormData({ ...formData, trade: e.target.value })}
                >
                  <option>Electrician</option>
                  <option>Plumber</option>
                  <option>Roofer</option>
                  <option>Builder</option>
                </select>
              </div>
              <div>
                <label className="block text-sm font-bold mb-2">Company Name</label>
                <input
                  type="text"
                  className="w-full bg-white border border-gray-300 rounded-lg px-4 py-3 outline-none focus:border-black"
                  placeholder="Dave's Ltd"
                  onChange={(e) => setFormData({ ...formData, company: e.target.value })}
                />
              </div>
            </div>

            <div>
              <label className="block text-sm font-bold mb-2">Job Description</label>
              <textarea
                className="w-full bg-white border border-gray-300 rounded-lg px-4 py-3 outline-none focus:border-black h-32 resize-none"
                placeholder="Describe the work..."
                onChange={(e) => setFormData({ ...formData, job: e.target.value })}
              ></textarea>
            </div>

            <div>
              <label className="block text-sm font-bold mb-3">Hazards</label>
              <div className="grid grid-cols-2 gap-3">
                {["Height Work", "Live Electricity", "Dust/Fumes", "Power Tools", "Manual Handling", "Asbestos"].map((h) => (
                  <button
                    key={h}
                    onClick={() => handleHazardToggle(h)}
                    className={`text-sm py-3 px-4 rounded-lg border font-medium transition-all ${
                      hazards.includes(h)
                        ? "bg-black text-white border-black shadow-md"
                        : "bg-white text-gray-600 border-gray-200 hover:border-gray-400"
                    }`}
                  >
                    {h}
                  </button>
                ))}
              </div>
            </div>

            <button
              onClick={generateRAMS}
              disabled={loading}
              className="w-full bg-black text-white font-bold text-lg py-4 rounded-xl hover:bg-gray-800 transition-all flex items-center justify-center gap-2 shadow-lg hover:shadow-xl disabled:opacity-50 disabled:cursor-not-allowed"
            >
              {loading ? <Loader2 className="animate-spin" /> : <HardHat />}
              {loading ? "Drafting Documents..." : "Generate RAMS"}
            </button>

            {generated && (
              <div className="bg-green-50 border border-green-200 rounded-xl p-4 flex items-center gap-4 text-green-800 animate-in fade-in slide-in-from-bottom-4">
                <CheckCircle className="w-8 h-8" />
                <div>
                  <p className="font-bold">Success!</p>
                  <p className="text-sm">Your PDF has been downloaded automatically.</p>
                </div>
              </div>
            )}
          </div>
        </div>
      </main>
    </div>
  );
}